custom tmp folder, code re-structure, some debug features, comments

diff --git a/asciicast2gif b/asciicast2gif
--- a/asciicast2gif
+++ b/asciicast2gif
@@ -2,52 +2,111 @@
 
 set -e
 
+# Set debugg according to $DEBUG env. variable
+# Debugging is disabled by default
 export DEBUG=${DEBUG:-0}
 
 path_to_self="${BASH_SOURCE[0]}"
 
 # Detect path
-if [ -L "$path_to_self" ]; then
+if [[ -L "$path_to_self" ]]; then
     asciicast2gif_dir="$(cd "$(dirname "$path_to_self")"/"$(dirname "$(readlink "$path_to_self")")" && pwd)"
 else
     asciicast2gif_dir="$(cd "$(dirname "$path_to_self")" && pwd)"
 fi
 
+# Check for the presence of 'node' executable, exit on error
 if ! type "node" >/dev/null 2>&1; then
     echo "error: Node.js not installed? Executable 'node' not found"
     exit 1
 fi
 
+# Check for the presence of 'convert' executable, exit on error
 if ! type "convert" >/dev/null 2>&1; then
     echo "error: ImageMagick not installed? Executable 'convert' not found"
     exit 1
 fi
 
+# Check for the presence of 'gifsicle' executable, exit on error
 if ! type "gifsicle" >/dev/null 2>&1; then
     echo "error: gifsicle not installed? Executable 'gifsicle' not found"
     exit 1
 fi
 
+# Check for the presence of './main.js' file, exit on error
 if [[ ! -f "${asciicast2gif_dir}/main.js" ]]; then
     echo "error: ${asciicast2gif_dir}/main.js not found. Build it with: lein cljsbuild once main"
     exit 1
 fi
 
+# Check for the presence of './page/page.js' file, exit on error
 if [[ ! -f "${asciicast2gif_dir}/page/page.js" ]]; then
     echo "error: ${asciicast2gif_dir}/page/page.js not found. Build it with: lein cljsbuild once page"
     exit 1
 fi
 
+# Check for the presence of 'mktemp' executable, exit on error
+if ! type "mktemp" >/dev/null 2>&1; then
+    echo "error: mktemp is required in order to use this program"
+    exit 1
+else
+    # Set the temporary path/folder to system default
+    tmppath="$(dirname $(mktemp -u))"
+fi
+
+# Define/initialize default variables
 theme="asciinema"
 speed=1
-scale=2
+scale=1
 width=""
 height=""
 
-while getopts ":w:h:t:s:S:" opt; do
+# If args count is less than 2, display the usage/help options
+if [[ $# -lt 2 ]]; then
+    echo "asciicast2gif - Generate GIF animations from asciicasts (asciinema recordings)"
+    echo
+    echo "usage: asciicast2gif [-t theme] [-T tmppath] [-s speed] [-S scale] [-w columns] [-h rows] <input-json-path-or-url> <output-gif-path>"
+    echo
+    echo "options:"
+    echo "  -t <theme>        color theme, one of: asciinema, tango, solarized-dark, solarized-light, monokai (default: $theme)"
+    echo "  -T <tmppath>      define substitute temporary path (default: '$tmppath')"
+    echo "  -s <speed>        animation speed (default: $speed)"
+    echo "  -S <scale>        image scale / pixel density (default: $scale)"
+    echo "  -w <columns>      clip terminal to specified number of columns (width)"
+    echo "  -h <rows>         clip terminal to specified number of rows (height)"
+    echo
+    exit 1
+fi
+
+# Verify tmppath settings and if we can read/write to it
+function checkTmp() {
+    # Check if tmppath directory exists, revert to system default on error
+    if [[ ! -d $tmppath ]]; then
+        echo "warning: provided temporary path is not a directory. Reverting to system default" >&2
+        # Revert to system default
+        tmppath="$(dirname $(mktemp -u))"
+    else
+        # Perform a write test using tmppath, revert to system default on error
+        rwtest=$(mktemp -p $tmppath -t tmp.rwtest.XXXXXX 2>/dev/null)
+        if [[ -f $rwtest ]]; then
+            rm -f $rwtest
+        else
+            echo "warning: cannot read/write to provided temporary path. Reverting to system default" >&2
+            # Revert to system default
+            tmppath="$(dirname $(mktemp -u))"
+        fi
+    fi
+}
+
+# Loop thru options
+while getopts ":w:h:t:T:s:S:" opt; do
     case $opt in
         t)
             theme=$OPTARG
+            ;;
+        T)
+            tmppath=$OPTARG
+            checkTmp
             ;;
         s)
             speed=$OPTARG
@@ -74,39 +133,29 @@ done
 
 shift $((OPTIND-1))
 
-if (($# != 2)); then
-    echo "asciicast2gif - Generate GIF animations from asciicasts (asciinema recordings)"
-    echo
-    echo "usage: asciicast2gif [-t theme] [-s speed] [-S scale] [-w columns] [-h rows] <input-json-path-or-url> <output-gif-path>"
-    echo
-    echo "options:"
-    echo "  -t <theme>        color theme, one of: asciinema, tango, solarized-dark, solarized-light, monokai (default: asciinema)"
-    echo "  -s <speed>        animation speed (default: 1)"
-    echo "  -S <scale>        image scale / pixel density (default: 2)"
-    echo "  -w <columns>      clip terminal to specified number of columns (width)"
-    echo "  -h <rows>         clip terminal to specified number of rows (height)"
-    exit 1
-fi
+# Test if variables are not empty.
+# Note: variables must be quoted for this test work
+if [[ -n "$width" ]]; then export WIDTH=$width; fi
+if [[ -n "$height" ]]; then export HEIGHT=$height; fi
 
-if [[ -n $width ]]; then
-    export WIDTH=$width
-fi
-
-if [[ -n $height ]]; then
-    export HEIGHT=$height
-fi
-
+# Set gifsicle options if they are non-existing
 if [[ -z $GIFSICLE_OPTS ]]; then
     export GIFSICLE_OPTS="-k 64 -O2 -Okeep-empty"
-
-    if gifsicle -h 2>/dev/null | grep -q lossy; then
+    # Check if gifsicle has loss option and use it
+    if [[ $(gifsicle -h 2>/dev/null|grep -q 'lossy') ]]; then
         export GIFSICLE_OPTS="$GIFSICLE_OPTS --lossy=80"
     fi
 fi
 
-tmp_dir=$(mktemp -d 2>/dev/null || mktemp -d -t 'asciicast2gif-tmp')
-trap 'rm -rf $tmp_dir' EXIT
+# Create a temporary directory. First try using
+# a template, then using system default naming
+tmp_dir=$(mktemp -p $tmppath -d -t 'asciicast2gif-tmp.XXXXXXXXXX' 2>/dev/null || mktemp -p $tmppath -d 2>/dev/null)
 
+# If debugging is disabled (default), set a trap on exit
+# signals in order to remove the temporary directory
+[[ $DEBUG -eq 0 ]] && trap 'rm -rf $tmp_dir' EXIT
+
+# Run the command
 node \
     $NODE_OPTS \
     "${asciicast2gif_dir}/main.js" \
@@ -117,4 +166,18 @@ node \
     $speed \
     $scale
 
-echo -e "\x1b[32m==> \x1b[0mDone."
+# Set nret to node return code
+nret=$?
+
+[[ $DEBUG -ne 0 ]] && echo "NodeJS return code: $nret" >&2;
+
+# Check return code of node run and act accordingly
+if [[ $nret -ne 0 ]]; then
+    echo -e "\x1b[1;38;5;196m==> \x1b[0mFailed"
+    # force an exit code in order to trigger the previously set trap
+    exit $nret
+else
+    echo -e "\x1b[32m==> \x1b[0mDone."
+    # force an exit code in order to trigger the previously set trap
+    exit $nret
+fi
